# Generated by Django 4.1.7 on 2023-05-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dostavka', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='dish_name_order',
        ),
        migrations.AlterField(
            model_name='productorder',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
