# Generated by Django 4.1.7 on 2023-05-25 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dostavka', '0002_remove_productorder_dish_name_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='price_order',
        ),
    ]
